db = "/app/strfry-db"

relay {
    bind = "0.0.0.0"
    port = 7777
    nofiles = 0

    info {
        name = "nostr-calendar-test-relay"
        description = "ephemeral test relay"
    }

    negentropy {
        enabled = true
    }
}
